name = "agriscope-website"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = "."

# Environment variables (if needed)
# [vars]
# API_KEY = "your-api-key-here"
